name: sort-actions
run-name: ${{ github.actor }} sort array
on:
  push:
    branches:
      - main
jobs:
  runs-sort-with-zulu-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java Sort.java